### ISSUE TITLE
Store tinyTerm2 does not come with vcruntime140.dll and msvcp140.dll

### ISSUE THREAD

**Issue by Efreak** [yongchaofan/tinyTerm2#1]
The c++ runtime dlls should probably be included in the Microsoft Store release. This is legal, as answered [on SO](https://stackoverflow.com/questions/35097193/can-i-bundle-the-visual-studio-2015-c-redistributable-dlls-with-my-applicatio). Alternatively, it's possible to [static link](https://social.msdn.microsoft.com/Forums/vstudio/en-US/ab187afb-3af0-44ba-a03c-dde9e5208a1a/static-link-to-vc-runtime?forum=vclanguage).

**Comment by yongchaofan** [comment]
Thanks, I will release version 1.1 soon, with vcruntime and msvcp statically linked.

**Comment by yongchaofan** [comment]
Version 1.1 released with statically linked vcruntime and msvcp.
