### ISSUE TITLE
add keyboard shortcut for disconnect

### ISSUE THREAD

**Issue by flyinggorilla** [yongchaofan/tinyTerm2#3]
Thanks for this terminal software, it is great because it just works and is super lightweight and slick. I use it mostly to connect via serial to microcontrollers. However, often i need to disconnect and reconnect (to free com port and then reconnect). A keyboard shortcut for disconnecting would be really appreciated.
Thx
FG

**Comment by yongchaofan** [comment]
Keyboard shortcut added for disconnecting in new release 2.1.0, 
Alt+d on Windows, Cmd+d on MacOS
